# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  project: SlowCheetah.sln      # path to Visual Studio solution or project
  
  # MSBuild verbosity level
  verbosity: normal

artifacts:
#  - path: 'BuildOutput\**\*.nupkg'
#  
#  - path: 'BuildOutput\**\*.vsix'
#  
#  - path: 'BuildOutput\**\*.dll'
#  
#  - path: 'BuildOutput\**\*.config'
